apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  releaseName: grafana
  targetNamespace: monitoring
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    name: grafana
    version: 4.6.3
    repository: https://kubernetes-charts.storage.googleapis.com
  values:
    service:
      type: LoadBalancer