apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  targetNamespace: monitoring
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    name: prometheus-operator
    version: 8.7.0
    repository: https://kubernetes-charts.storage.googleapis.com
  values:
    grafana:
      ingress:
        enabled: true
      