apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: kube-system
spec:
  releaseName: loki
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: 0.32.0
  values:
    grafana:
      enabled: true
      service:
        type: LoadBalancer
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth
        hosts:
          - grafana.lab.markushartmann.dev
      sidecar:
        datasources:
          enabled: false
        dasboards:
          enabled: false