apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  releaseName: metallb
  targetNamespace: metallb
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    name: metallb
    version: 0.12.0
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.178.181-192.168.178.250