apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  releaseName: nginx-ingress
  targetNamespace: kube-system
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
    version: 1.30.0
  values:
    controller:
      service:
        type: LoadBalancer
        annotations: dev.inlets.manage=true
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm
        tag: 0.28.0
    defaultBackend:
      image:
        repository: k8s.gcr.io/defaultbackend-arm