apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tunnels.inlets.inlets.dev
spec:
  group: inlets.inlets.dev
  version: v1alpha1
  names:
    kind: Tunnel
    plural: tunnels
  scope: Namespaced
  additionalPrinterColumns:
  - name: Service
    type: string
    JSONPath: .spec.serviceName
  - name: HostStatus
    type: string
    JSONPath: .status.hostStatus
  - name: HostIP
    type: string
    JSONPath: .status.hostIP
  - name: HostID
    type: string
    JSONPath: .status.hostId
  - name: Tunnel
    type: string
    JSONPath: .spec.client_deployment.name


