apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  releaseName: traefik
  targetNamespace: traefik-system
  timeout: 300
  resetValues: false
  wait: false
  forceUpgrade: false
  chart:
    name: traefik
    version: 1.86.1
    repository: https://kubernetes-charts.storage.googleapis.com
  values:
    rbac:
      enabled: true
    dashboard:
      enabled: true
      domain: ingress-dashboard.lab.markushartmann.dev